name: tap_dana_cuan
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  google_mobile_ads: ^5.1.0

flutter:
  uses-material-design: true
