name: mountain_hunter
description: Bubble DANA Cuan V2 - Bubble Terbang
publish_to: 'none'
version: 2.0.0+2
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  audioplayers: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon.png
