import 'dart:math';import 'package:flutter/material.dart';import 'package:url_launcher/url_launcher.dart';
void main()=>runApp(const MaterialApp(debugShowCheckedModeBanner:false,home:G()));
class Ball{double x,y,by,s,p;Color c;Ball(this.x,this.y,this.by,this.s,this.p,this.c);}
class G extends StatefulWidget{const G({super.key});@override State<G> createState()=>_G();}
class _G extends State<G> with SingleTickerProviderStateMixin{
int k=486;int hit=0;List<Ball> b=[];final r=Random();late AnimationController ac;double t=0;
@override void initState(){super.initState();ac=AnimationController(vsync:this,duration:const Duration(milliseconds:16))..repeat()..addListener(lo);ib();}
void ib(){b.clear();for(int i=0;i<15;i++){b.add(Ball(0.05+(i%5)*0.18+r.nextDouble()*0.05,0.2+(i~/5)*0.2,0.2+(i~/5)*0.2,0.6+r.nextDouble(),r.nextDouble()*6,[const Color(0xFFF7D060),const Color(0xFF98D8AA),const Color(0xFFB08BBB),const Color(0xFFEF9A9A),const Color(0xFF90CAF9)][i%5]));}}
void lo(){t+=0.02;setState(()=>b.forEach((e)=>e.y=e.by+sin(t*e.s+e.p)*0.1));}
void tap(int i){
setState((){k+=1;hit+=1;b.removeAt(i);b.add(Ball(r.nextDouble()*0.8+0.05,r.nextDouble()*0.6+0.15,r.nextDouble()*0.6+0.15,0.6+r.nextDouble(),r.nextDouble()*6,Colors.primaries[r.nextInt(Colors.primaries.length)]));});
if(hit%20==0){int bo=30+r.nextInt(21);showDialog(context:context,barrierDismissible:false,builder:(_)=>AlertDialog(shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(20)),title:const Text('BONUS IKLAN!'),content:Text('Mantap! Sudah 20x tap\nDapat bonus $bo koin!'),actions:[ElevatedButton(style:ElevatedButton.styleFrom(backgroundColor:Colors.orange),onPressed:(){setState(()=>k+=bo);Navigator.pop(context);},child:Text('AMBIL $bo',style:const TextStyle(color:Colors.white)))]));}
}
@override Widget build(BuildContext c){return Scaffold(body:Container(decoration:const BoxDecoration(gradient:LinearGradient(colors:[Color(0xFF9AD9FF),Color(0xFFBFF0BE)])),child:SafeArea(child:Column(children:[Padding(padding:const EdgeInsets.all(10),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Container(padding:const EdgeInsets.symmetric(horizontal:14,vertical:7),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20)),child:Text('$k Koin',style:const TextStyle(fontWeight:FontWeight.bold))),Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:5),decoration:BoxDecoration(color:Colors.black54,borderRadius:BorderRadius.circular(12)),child:Text('$hit / 20',style:const TextStyle(color:Colors.white,fontSize:12)))])),Expanded(child:Stack(children:[for(int i=0;i<b.length;i++)Positioned(left:b[i].x*MediaQuery.of(c).size.width,top:b[i].y*400,child:GestureDetector(onTap:()=>tap(i),child:Container(width:64,height:64,decoration:BoxDecoration(color:b[i].c,shape:BoxShape.circle,border:Border.all(color:Colors.white,width:3)),child:const Center(child:Text('\$',style:TextStyle(color:Colors.white,fontWeight:FontWeight.bold))))))])),Container(margin:const EdgeInsets.all(12),width:double.infinity,child:ElevatedButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>DPage(coin:k,onDone:(v){setState(()=>k-=v);}))),child:const Text('TUKAR SALDO')))]))));}
}
class DPage extends StatefulWidget{final int coin;final Function(int) onDone;const DPage({super.key,required this.coin,required this.onDone});@override State<DPage> createState()=>_D();}
class _D extends State<DPage>{
final hp=TextEditingController(text:'08');int sel=-1;String wa='6281234567890';var nom=[100,500,1000,5000,10000,50000];
void tarik()async{if(hp.text.length<10||sel==-1)return;if(widget.coin<nom[sel])return;final url=Uri.parse('https://wa.me/$wa?text=Halo%20Admin%20mau%20tarik%20Rp${nom[sel]}%20DANA%20${hp.text}');if(await canLaunchUrl(url)){await launchUrl(url,mode:LaunchMode.externalApplication);widget.onDone(nom[sel]);if(mounted)Navigator.pop(context);}}
@override Widget build(BuildContext c){return Scaffold(appBar:AppBar(title:const Text('Tukar DANA')),body:Padding(padding:const EdgeInsets.all(16),child:Column(children:[TextField(controller:hp,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'No DANA',border:OutlineInputBorder())),const SizedBox(height:12),Wrap(spacing:8,runSpacing:8,children:[for(int i=0;i<nom.length;i++)ChoiceChip(label:Text('Rp${nom[i]}'),selected:sel==i,onSelected:widget.coin>=nom[i]?(v){setState(()=>sel=i);}:null)]),const SizedBox(height:20),SizedBox(width:double.infinity,child:ElevatedButton.icon(icon:const Icon(Icons.chat),label:const Text('TARIK VIA WHATSAPP'),style:ElevatedButton.styleFrom(backgroundColor:const Color(0xFF25D366),foregroundColor:Colors.white,padding:const EdgeInsets.symmetric(vertical:16)),onPressed:tarik))])));}}
